const birdsList = [
  [
    {
      id: 1,
      name: 'Утка',
      translation: 'Anatinae',
      image: 'https://live.staticflickr.com/65535/50029195198_910a915a24.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/FHQVLXJQKW/XC468962-Falkland%20Steamer%20Duck%206.mp3',
      description: 'Утки — это птицы средних и небольших размеров с относительно короткой шеей и цевкой, покрытой спереди поперечными щитками.',
    },
    {
      id: 2,
      name: 'Воробей',
      translation: 'Passer domesticus',
      description: 'Являются самыми известными пернатыми, предпочитающими гнездиться рядом с людьми. Воробьев легко узнать по пестрому оперению и задорному чириканью.',
      image: 'https://live.staticflickr.com//65535//49366595303_06cf65b07e.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/GABAHHYWYR/XC583867-VOC_200818-1045%20House%20Sparrow.mp3',
    },
    {
      id: 3,
      name: 'Дятел',
      translation: 'Dendrocopos',
      image: 'https://live.staticflickr.com/65535/50107403761_43950068b2.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YWRKFXUDUR/XC507990-100%20Woodpecker%20-%20Rufous-bellied%20%28Dendrocopos%20h.%20hyperythrus%29%20Song%20NOV%201728h%202450m%20MtVictoria_GI_1562.mp3',
      description: 'Дятлы иногда используют в качестве барабана пустые консервные банки и куски железа для того, чтобы их барабанная дробь звучала достаточно далеко: так они призывают к себе других дятлов.',
    },
    {
      id: 4,
      name: 'Сова',
      translation: 'Strigiformes',
      image: 'https://live.staticflickr.com/65535/50217605031_541e393d58.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC534798-Berguv_09.mp3',
      description: 'Краткая характеристика: крупная голова, большие круглые глаза спереди головы, клюв короткий, хищный. Охотится ночью, оперение мягкое, полёт бесшумный, когти длинные и острые, окрас маскирующий.',
    },
    {
      id: 5,
      name: 'Бородач',
      translation: 'Gypaetus barbatus',
      image: 'https://live.staticflickr.com/65535/50242074586_fd085d65f8.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/UXGZWVYDFE/XC144936-Gypaetus%20barbatus_pos%C3%A9_C_F%20Deroussen_2013042300.mp3',
      description: 'Места обитания — скалы и открытые пространства гор на высоте 500—4000 м. Отдельные особи наблюдались над Эверестом на высоте более 7300 м и, вероятно, даже более 7600 м.',
    },
    {
      id: 6,
      name: 'Сорока',
      translation: 'Pica pica',
      image: 'https://live.staticflickr.com/65535/50260415942_1494ab1280.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/KTBMJVGTZO/XC542352-Elster_AC_NW_04.04.2020_21.13Uhr.mp3',
      description: 'Сороки населяют всю Европу от Нордкапа в Скандинавии до южных оконечностей Испании и Греции. Она отсутствует только на нескольких островах Средиземного моря. Также населяет части прибрежных областей Марокко, Алжира, Туниса на севере Африки. Сорока — это оседлая птица, но в Скандинавии также и перелётная.',
    },
  ],
  [
    {
      id: 1,
      name: 'Клёст',
      translation: 'Loxia',
      image: 'https://live.staticflickr.com/65535/50248165662_9c6472a822.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC512399-St%C3%B6rre%20korsn%C3%A4bb_08.mp3',
      description: 'В прошлом клесты благодаря «попугайной» внешности были популярны у птицеловов: шарманщики в XIX веке обучали этих птиц вытаскивать «счастливые билетики». На Урале в военные годы мясо этих птиц употребляли в пищу, причем поймать клестов можно было (в урожайные на еловые шишки годы) обычным ящиком.',
    },
    {
      id: 2,
      name: 'Снегирь',
      translation: 'Pyrrhula pyrrhula',
      image: 'https://live.staticflickr.com/65535/50249508672_fa918448eb.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/HVLWWLJFGV/XC574303-Bouvreuil%20pivoine%20cri%20poligny.mp3',
      description: 'Питается снегирь семенами, почками, некоторыми паукообразными и ягодами (в частности, рябиной). Кормясь ягодами, выедает из них семена, оставляя мякоть. Птенцов выкармливает в основном растительными кормами, добавляя насекомых и ягоды.',
    },
    {
      id: 3,
      name: 'Щегол',
      translation: 'Carduelis carduelis',
      image: 'https://live.staticflickr.com/65535/50267082148_fe8c616cda.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC584319-Chardonneret%20elegant%20quemandage%20%2B.mp3',
      description: 'Песня – звонкие негромкие и легко запоминающиеся  трели. Птенцов щеглы выкармливают насекомыми.',
    },
    {
      id: 4,
      name: 'Дрозд',
      translation: 'Turdus',
      image: 'https://live.staticflickr.com/65535/50253713018_d09bf501ba.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/OOECIWCSWV/XC509167-LS104776%20Groundscraper%20Thrush%20song%20A.mp3',
      description: 'Распространены в Европе, Азии и Америке; завезены в Новую Зеландию. На зиму северные виды улетают на юг, собираясь большими стаями.',
    },{
      id: 5,
      name: 'Чиж',
      translation: 'Carduelis spinus',
      image: 'https://live.staticflickr.com/65535/50193479447_dc21ca30b5.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/TFOGOENSTQ/XC567720-200120_1686%201105%20Zeisige.%20Berlin%2C%20Spandauer%20Forst.%20Stephan%20Risch.mp3',
      description: 'Распространён в Евразии, как правило, в хвойных лесах. Чижей часто держат в домашних условиях, в клетках, ради их пения.',
    },
    {
      id: 6,
      name: 'Воробей',
      translation: 'Passer domesticus',
      description: 'Являются самыми известными пернатыми, предпочитающими гнездиться рядом с людьми. Воробьев легко узнать по пестрому оперению и задорному чириканью.',
      image: 'https://live.staticflickr.com//65535//49366595303_06cf65b07e.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/GABAHHYWYR/XC583867-VOC_200818-1045%20House%20Sparrow.mp3',
    },
  ],
  [
    {
      id: 1,
      name: 'Ласточка',
      translation: 'Hirundo rustica',
      image: 'https://live.staticflickr.com/65535/50266899186_b51c2fe43f.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC584489-Hirondelle%20rustique%20divers%20cris%20de%20vol%20%2B%2B.mp3',
      description: 'Небольшая птица, длина тела 14,6—19,9 см, размах крыльев 31,8—34,3 см. Вес птицы составляет 17—20 г. Окраска сверху сине-чёрная с металлическим отблеском, снизу бледно-бежевая.',
    },
    {
      id: 2,
      name: 'Грач',
      translation: 'Corvus frugilegus',
      image: 'https://live.staticflickr.com/65535/50210170783_39751a9e72.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YEGMFPTPKL/XC572103-Pipping%20bird%201.mp3',
      description: 'Грачи всеядны, но главным образом питаются червями и личинками насекомых, которых они находят, копаясь в земле своим крепким клювом. Любят большими стаями следовать за пашущими землю.',
    },
    {
      id: 3,
      name: 'Синица',
      translation: 'Parus',
      image: 'https://live.staticflickr.com/65535/50266770852_a533527136.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/AGCYXCXXSH/XC573597-great%20tit%205%203.mp3',
      description: 'Синица обладает богатым голосовым репертуаром — специалисты выделяют до 40 вариаций издаваемых ею звуков. При этом одна и та же особь одновременно способна чередовать три — пять вариантов, различных по ритму, тембру, относительной высоте звуков и количеству слогов. Особенно активен самец, поющий в течение почти всего года, за исключением поздней осени и ранней зимы.',
    },
    {
      id: 4,
      name: 'Дятел',
      translation: 'Dendrocopos',
      image: 'https://live.staticflickr.com/65535/50107403761_43950068b2.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YWRKFXUDUR/XC507990-100%20Woodpecker%20-%20Rufous-bellied%20%28Dendrocopos%20h.%20hyperythrus%29%20Song%20NOV%201728h%202450m%20MtVictoria_GI_1562.mp3',
      description: 'Дятлы иногда используют в качестве барабана пустые консервные банки и куски железа для того, чтобы их барабанная дробь звучала достаточно далеко: так они призывают к себе других дятлов.',
    },{
      id: 5,
      name: 'Поползень',
      translation: 'Sitta europaea',
      image: 'https://live.staticflickr.com/65535/50267878506_7d03f95baa.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/RVLNPQSYVW/XC572075-2020%2C06.27_7.03%28eurasian%20nuthatch%29.mp3',
      description: 'Обитает в лесах — как лиственных, так смешанных и хвойных, при этом предпочитает районы с изобилием высокоствольных и старых деревьев, где находит себе пропитание.',
    },
    {
      id: 6,
      name: 'Зяблик',
      translation: 'Fringilla coelebs',
      image: 'https://live.staticflickr.com/65535/50265775358_e25198cce1.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/TFJFYTDAWQ/XC581621-Madeira%20Chaffinch%20-%20call%201.mp3',
      description: 'Распространён в Европе, Западной Азии и Северной Африке; расселяется на Востоке. Одна из самых многочисленных птиц в России. Обитает в лесах и парках всех типов, часто у самого жилья человека.',
    },
  ],
  [
    {
      id: 1,
      name: 'Орёл',
      translation: 'Aquila',
      image: 'https://live.staticflickr.com/65535/50217751951_61672f78a2.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/KTBTZAHSXF/10_Aquila_nipalensis_al02D85.mp3',
      description: 'Гнездятся на земле, скалах или деревьях. Питаются мелкими и средней величины позвоночными (высматривают, паря в воздухе, или подкарауливают, сидя на возвышенном месте), иногда падалью',
    },
    {
      id: 2,
      name: 'Ястреб',
      translation: 'Accipitrinae',
      image: 'https://live.staticflickr.com/65535/50213713291_15dcee72c8.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YWWWUBVAJF/XC427037-Accipiter%20superciliosus%20superciliosus-Caio%20Brito-%28Parecis-RO%29-BRITO298.mp3',
      description: 'Происхождение слово ястреб на разных языках связано с определениями «острый», «резкий», «быстрый», «быстролетящий», что указывает на характер и образ жизни птицы.',
    },
    {
      id: 3,
      name: 'Канюк',
      translation: 'Buteo buteo',
      image: 'https://live.staticflickr.com/65535/50214628207_595f87ff62.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/LHCOINSOBZ/XC570072-Parella%20Buteo%20buteo%20voando%20sobre%20maizal%2013%20horas%20sol%20cantalarrana%20.mp3',
      description: 'Предпочитает леса, чередующиеся с лугами, полянами. Охотится на открытых пространствах, медленно паря в воздухе или чаще всего с засады на возвышении.',
    },
    {
      id: 4,
      name: 'Сова',
      translation: 'Strigiformes',
      image: 'https://live.staticflickr.com/65535/50217605031_541e393d58.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC534798-Berguv_09.mp3',
      description: 'Краткая характеристика: крупная голова, большие круглые глаза спереди головы, клюв короткий, хищный. Охотится ночью, оперение мягкое, полёт бесшумный, когти длинные и острые, окрас маскирующий.',
    },{
      id: 5,
      name: 'Цапля',
      translation: 'Ardea',
      image: 'https://live.staticflickr.com/65535/50263169702_6e50967941.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YESYDXYEZD/XC547455-heron_cendre_gacholle.mp3',
      description: 'Охотятся они, неподвижно стоя в воде или подкрадываясь к жертве на мелководье, а затем хватая её быстрым рывком. В полёте они медлительны.',
    },
    {
      id: 6,
      name: 'Каракара',
      translation: 'Caracara',
      image: 'https://live.staticflickr.com/65535/49757041908_92e810ce3c.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/MAZXYOGLXR/XC518300-Black%20Caracara.mp3',
      description: 'Пища разнообразна: от насекомых и червей до мелких зверьков, лягушек и ящериц. Часто поедает падаль, отбирает добычу у других птиц.',
    },
  ],
  [
    {
      id: 1,
      name: 'Гриф',
      translation: 'Gyps',
      image: 'https://live.staticflickr.com/65535/50214552168_4ba4ca6ffe.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/OOECIWCSWV/XC346817-LS103155%20White-backed%20Vulture%20call%20B.mp3',
      description: 'Типичные падальщики, выделяются преимущественно тёмным оперением, неоперённой головой (многие — неоперённой шеей) и длинными и широкими крыльями',
    },
    {
      id: 2,
      name: 'Стервятник',
      translation: 'Neophron percnopterus',
      image: 'https://live.staticflickr.com/65535/50263260941_64fdabd9d0.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/ILUHRFXDNU/percnoptere%20dEgypte%20chickcall.mp3',
      description: 'Стервятники — весьма социальные животные и живут в небольших группах. В саваннах они часто встречаются лишь парами. У падали они в большинстве случаев являются последними, кому достаются какие-либо куски.',
    },
    {
      id: 3,
      name: 'Африканский сип',
      translation: 'Gyps rueppellii',
      image: 'https://live.staticflickr.com/65535/49850868896_bcedc9bf63.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC423953-Vautour%20fauve%20gemissement%203.mp3',
      description: 'Возможно, наиболее высоко летающие птицы: известен случай столкновения птицы с самолётом на высоте 11 277 м.',
    },
    {
      id: 4,
      name: 'Марабу',
      translation: 'Leptoptilos',
      image: 'https://live.staticflickr.com/65535/50244449332_59c4783b68.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/OOECIWCSWV/XC300421-LS_50712%20Marabou%20calls%20A.mp3',
      description: 'Марабу может отнять добычу у некоторых хищников, например, орланов. Также марабу может поедать яйца и детёнышей крокодилов.',
    },{
      id: 5,
      name: 'Бородач',
      translation: 'Gypaetus barbatus',
      image: 'https://live.staticflickr.com/65535/50242074586_fd085d65f8.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/UXGZWVYDFE/XC144936-Gypaetus%20barbatus_pos%C3%A9_C_F%20Deroussen_2013042300.mp3',
      description: 'Места обитания — скалы и открытые пространства гор на высоте 500—4000 м. Отдельные особи наблюдались над Эверестом на высоте более 7300 м и, вероятно, даже более 7600 м.',
    },
    {
      id: 6,
      name: 'Андский кондор',
      translation: 'Vultur gryphus',
      image: 'https://live.staticflickr.com/65535/50204764337_f84439970a.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/DISAQFOZJP/CONDOR%20Andean_20_CRAR-UNORCH_Santiago_CH_SEP00_Guillermo%20Egli%20%28Egli%202002%29.mp3',
      description: 'Считается самой крупной летающей птицей Западного полушария. Контрастное оперение сочетает в себе чёрный и белый цвета, в последний окрашены широкие каймы второстепенных маховых перьев и кроющих перьев крыла, а также пуховой воротник. ',
    },
  ],
  [
    {
      id: 1,
      name: 'Сорока',
      translation: 'Pica pica',
      image: 'https://live.staticflickr.com/65535/50260415942_1494ab1280.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/KTBMJVGTZO/XC542352-Elster_AC_NW_04.04.2020_21.13Uhr.mp3',
      description: 'Сороки населяют всю Европу от Нордкапа в Скандинавии до южных оконечностей Испании и Греции. Она отсутствует только на нескольких островах Средиземного моря. Также населяет части прибрежных областей Марокко, Алжира, Туниса на севере Африки. Сорока — это оседлая птица, но в Скандинавии также и перелётная.',
    },
    {
      id: 2,
      name: 'Ворон',
      translation: 'Corvus corax',
      image: 'https://live.staticflickr.com/65535/50263220802_4b35688775.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/YDQKMZXDRL/XC570428-DM673420_Kra-Nest_cut_rau1_Noise.mp3',
      description: 'Ворон — одна из немногих птиц, способных выполнять манёвры, аналогичные авиационным фигурам пилотажа: управляемую бочку и полубочку.',
    },
    {
      id: 3,
      name: 'Утка',
      translation: 'Anatinae',
      image: 'https://live.staticflickr.com/65535/50029195198_910a915a24.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/FHQVLXJQKW/XC468962-Falkland%20Steamer%20Duck%206.mp3',
      description: 'Утки — это птицы средних и небольших размеров с относительно короткой шеей и цевкой, покрытой спереди поперечными щитками.',
    },
    {
      id: 4,
      name: 'Фазан',
      translation: 'Phasianus colchicus',
      image: 'https://live.staticflickr.com/65535/50267530886_fd7b3f3781.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/EDRTTPSCEN/XC541189-Faisan%20de%20Colchide%202004030CA%20Marais%20d%27Harchies.mp3',
      description: 'Фазан является национальной птицей Грузии, чьё почитание связано с древним Колхидским царством.',
    },{
      id: 5,
      name: 'Сойка',
      translation: 'Garrulus glandarius',
      image: 'https://live.staticflickr.com/65535/50261866723_7bea5fff01.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/ITHRUQEQCF/XC584786-0825_1656_Ghiandaia%20imita%20Poiana.mp3',
      description: 'Слово сойка — уменьшительная форма от древнерусского названия этой птицы «соя». Предполагается, что название родственно глаголу «сиять» и дано птице за яркое оперение.',
    },
    {
      id: 6,
      name: 'Дрофа',
      translation: 'Otis tarda',
      image: 'https://live.staticflickr.com/65535/49997458313_b6a1f26ab5.jpg',
      audio: 'https://www.xeno-canto.org/sounds/uploaded/OOECIWCSWV/XC508920-LS104679%20White-bellied%20Bustard%20song%20A.mp3',
      description: 'Дрофа питается растительной и животной пищей — травами, зеленью культурных растений, насекомыми, иногда ящерицами и мышевидными грызунами. Гнездится с апреля по июнь, в кладке — 1—3 яйца желтоватой, зеленоватой или голубоватой окраски со сложным рисунком.',
    },
  ],
]

export default birdsList;